"""Initial migration

Revision ID: 392d2f17f14e
Revises: 
Create Date: 2024-12-20 10:47:08.706496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392d2f17f14e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
