"""Added logic for 10+ points games

Revision ID: 6381ac09f503
Revises: 72bd135be2ea
Create Date: 2024-10-20 13:25:20.297623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6381ac09f503'
down_revision = '72bd135be2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_10', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('points_10')

    # ### end Alembic commands ###
