"""Add close shot attribute

Revision ID: 72bd135be2ea
Revises: 82c11998431a
Create Date: 2024-10-20 09:11:03.449612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bd135be2ea'
down_revision = '82c11998431a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_shot', sa.Integer(), nullable=True))

    with op.batch_alter_table('player_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_shot', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_targets', schema=None) as batch_op:
        batch_op.drop_column('close_shot')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('close_shot')

    # ### end Alembic commands ###
