"""Add PlayerTargets table

Revision ID: 81e02bb9ce98
Revises: f9956978df5b
Create Date: 2024-10-03 16:39:04.533023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e02bb9ce98'
down_revision = 'f9956978df5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('attribute_targets', sa.JSON(), nullable=True),
    sa.Column('badge_targets', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_targets')
    # ### end Alembic commands ###
