"""Add cascade delete to players with named constraint

Revision ID: cc642208f245
Revises: de97f8e76c0d
Create Date: 2024-09-17 14:31:17.227222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc642208f245'
down_revision = 'de97f8e76c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_player', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_player', type_='foreignkey')

    # ### end Alembic commands ###
