"""Add UserSettings fields

Revision ID: f9956978df5b
Revises: e8a65057cea3
Create Date: 2024-09-18 11:38:51.235859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9956978df5b'
down_revision = 'e8a65057cea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rebounds_20', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rebounds_10', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assists_20', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assists_10', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('assists_10')
        batch_op.drop_column('assists_20')
        batch_op.drop_column('rebounds_10')
        batch_op.drop_column('rebounds_20')

    # ### end Alembic commands ###
